apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  ports:
  # targetPort means pod port
    - targetPort: 80
  #  port means service port
      port: 80
      nodePort: 30008
  selector:
      type: front-end

